### ISSUE TITLE
NLP pour avoir le diff entre le projet de loi / loi actuelle

### ISSUE THREAD

**Issue by pierreN** [regardscitoyens/the-law-factory-parser#125]
Bonjour et merci pour ce travail qui est tout bonnement génial. 

J’ai essayé de regarder dans le projet, mais il me semble que cette question n’a pas été abordée :

est ce que vous avez la volonté de traiter le texte des projets de loi pour les afficher dans un format clair aux non-initiés, ou l’ont voit la différence entre la loi actuelle et les modifications que propose le projet de loi ? 
Quelque chose du style : https://parol-production.herokuapp.com/ ? 

Vu que vous gérez déjà `git`, on pourrait imaginer quelque chose du style https://archeo-lex.fr/codes ou les propositions de loi ne sont que des pull request sur les répertoires existant. 

Et le top serait de gérer aussi les amendements, histoire de pouvoir savoir quel député fait quoi avec un simple `git blame`.

L’idée est assez évidente et j’imagine que vous y avez déjà pensé, mais curieux d’avoir votre retour là-dessus. 

Merci!

**Comment by boogheta** [comment]
Bonjour @PierreN !
C'est évidemment le graal imaginé dès les toutes premières réflexions autour de ce projet, mais j'ai peur que nous en soyons encore un petit peu loin. La Fabrique juqu'ici ne fait que retracer les évolutions du texte version après version et d'associer les amendements correspondants, mais pas encore l'application automatique des amendements au projet de loi et a fortiori pas non plus sur les codes de loi eux mêmes.
Le projet [duralex](https://github.com/Legilibre/DuraLex) de @promethe42 et @Seb35 de @Legilibre (les gens d'archeo-lex) prépare actuellement le terrain pour cela et il y a déjà un prototype fonctionnel testable ici https://archeo-lex.fr/durafront/
Je me permets donc de fermer cette issue ici et t'inviter à aller voir de ce côté, mais n'hésite pas à prolonger la discussion ici !

**Comment by Seb35** [comment]
Sur l’application des amendements, comme @boogheta en a parlé, c’est le projet [DuraLex](https://github.com/Legilibre/DuraLex) qui "lit" l’amendement et en fabrique un arbre sémantique, qui décrit les modifications de base (ajout/suppression/modification) sur telle ou telle partie du texte cible. Ensuite, le projet frère [SedLex](https://github.com/Legilibre/SedLex) prend cet arbre sémantique et applique les modifications sur le texte cible (le projet de loi dans le cas des amendements), et on peut alors créer le diff sur l’article du projet de loi. Vu que les projets de loi sont eux-mêmes souvent des textes modificateurs notamment de codes juridiques, il faut répéter ces mêmes opérations sur les codes pour obtenir le résultat ultime.

Pour le graal git-blame, quand DuraLex/SedLex fonctionnera bien, ça deviendra envisageable, mais se posera alors la question (qui demandera aussi du travail) d’une bonne interface visuelle, surtout si on veut faire un "double git-blame" sur un code pour remonter à l’amendement (voire un triple dans le cas des sous-amendements).

Sur l’actualité, j’ai créé en août l’interface [metslesliens-ui](https://archeo-lex.fr/metslesliens/) comme "IDE" de la grammaire des liens, qui est une sous-partie de DuraLex, du fait du constat que la principale difficulté pour améliorer fortement DuraLex est la difficulté d’appréhension du corpus de règles et le fait qu’il faudrait des tests de non-régression (pas forcément empêcher strictement les régressions mais au moins statistiquement sur un corpus un peu important). Un tel environnement devrait permettre de faciliter le développement de la grammaire [PEG.js](https://pegjs.org) de DuraLex. Ce travail de conversion en une grammaire PEG avait été [commencé l’année dernière](https://github.com/Legilibre/DuraLex/tree/peg) avec @promethe42 lors d’un hackathon organisé par @regardscitoyens mais ça n’a pas beaucoup avancé depuis (sur le fond de l’écriture de la grammaire).

**Comment by pierreN** [comment]
Wow, en effet, beaucoup de travail sur ce sujet et j’étais passe totalement a cote de ces projets, merci pour la réponse.

Je vais regarder un peu tout ça et voir ce que je pourrais apporter ! (si je peux apporter quelque chose^^)
