### ISSUE TITLE
Duplicate article title found

### ISSUE THREAD

**Issue by davidbgk** [regardscitoyens/the-law-factory-parser#126]
Hey there 👋 ,

The parsing of [that page](https://www.senat.fr/leg/pjl18-218.html) raises:

```
Exception: ('Duplicate article title found: %s', '56 bis')
```

Which seems legit given that `Article 56 bis ` is present twice. But maybe it should raise a warning instead of stopping the parsing completely for the remaining valid articles?

What do you think? How do you handle these cases?

Thanks!

**Comment by boogheta** [comment]
Voilà ça crashe désormais avec une tlfp.tools.parse_texte.TextParsingFailedException

**Comment by davidbgk** [comment]
Nice! Merci 👍

**Comment by boogheta** [comment]
Pourras-tu faire remonter le souci au Sénat par ailleurs ? Ils sont généralement plutôt réactifs et ça permettrait de clore pour de vrai cette issue ;)

**Comment by davidbgk** [comment]
Courriel envoyé ;)

**Comment by RouxRC** [comment]
Cool thx!

**Comment by davidbgk** [comment]
Côté Sénat :

> Nous allons y remédier de notre côté

Côté AN :

> Renseignement pris auprès de la division des Lois de l'Assemblée nationale, il ne s'agit pas d'un accent mais d'un point. Le caractère "I majuscule avec un point" est, dans certains cas, inséré afin d'éviter toute ambiguïté (permet de le distinguer du chiffre 1).

Ce que l'on a fait de notre côté :

https://github.com/betagouv/zam/pull/679

**Comment by boogheta** [comment]
J'adore le coup de l'AN qui fait un hack dégueu parce que tu vois c'est pratique, mais qui prévient pas le Sénat, dont le code pète sur l'encoding de ce hack, et du coup fallback en générant un truc faux ! :D 
De notre côté, j'avais déjà ajouté au parser que si on trouvait un article İ on le réécrivait en article I donc je ne pense rien ajouter de plus a priori (cf https://github.com/regardscitoyens/the-law-factory-parser/commit/d931ecea958961c3afbee4aeecfd29527b90c938)

**Comment by davidbgk** [comment]
🤷‍♂
