### ISSUE TITLE
wrong chmod on .sh files

### ISSUE THREAD

**Issue by promethe42** [regardscitoyens/the-law-factory-parser#48]
Hello,

`*.sh` files are not marked as executable when cloning the repository.

`chmod +x *.sh && chmod +x script/*.sh`

should fix this issue.

Regards,

**Comment by promethe42** [comment]
I just saw they're not supposed to be executed directly. Is there a reason to run them through `bash` instead of running them directly?

**Comment by teymour** [comment]
No reasons, it's just a habit we have in this project.

**Comment by RouxRC** [comment]
obsolete as well
