### ISSUE TITLE
toward a text edits parser

### ISSUE THREAD

**Issue by promethe42** [regardscitoyens/the-law-factory-parser#52]
Hello,

my goal is to be able to render "augmented" law texts.
I understand that today the exhaustive data is only available when the law proposition has been voted and fully redacted.
But I need to be have the whole text and the corresponding metadata before it is voted/officially published.

I've been reading the [parse_texte.py](https://github.com/regardscitoyens/the-law-factory-parser/blob/master/scripts/collectdata/parse_texte.py) script and I was wondering why you're using regexp all over the place instead of a cleaner lexer/parser => AST method.

Is it because you tried building an AST and failed because the formatting of the law texts is too fuzzy?

Do you have any existing/current work on the matter?

I might try to do that if you don't mind...

Thank you,

**Comment by boogheta** [comment]
The parser handles documents from different sources (AN, Sénat & Legifrance) and very different formattings (propositions, texts voted in commission, "petites lois", ...) and various manual inputs that only regexp could handle generically properly.
You should be able to process most text bills html using parse_texte.py, but feel free to try and build another parser (let us know about it when finished then!)

**Comment by boogheta** [comment]
PS: the parser was written for the previous AN webpages for documents, which are still accessible following a few rules:

For instance:
http://www2.assemblee-nationale.fr/documents/notice/14/projets/pl3679/%28index%29/projets-loi
is actually
http://www.assemblee-nationale.fr/14/projets/pl3679.asp

And the parser is using the url saved as the filename of the html, so for instance for the above url, you need to do something such as: 
```bash
curl "http://www.assemblee-nationale.fr/14/projets/pl3679.asp" > /tmp/http%3A%2F%2Fwww.assemblee-nationale.fr%2F14%2Fprojets%2Fpl3679.asp
python scripts/collectdata/parse_texte.py /tmp/http%3A%2F%2Fwww.assemblee-nationale.fr%2F14%2Fprojets%2Fpl3679.asp > /tmp/egalite.json
```

**Comment by promethe42** [comment]
I got some time to kill in the plane so I started working on an actual lexer/parser.
It can already procude this kind of output:

```

  "ast": {
    "children": [
      {
        "type": "article",
        "children": [
          {
            "type": "article-edit",
            "children": [
              {
                "type": "article-reference",
                "articleId": "L. 260",
                "children": [
                  {
                    "type": "code-reference",
                    "codeName": "code électoral"
                  }
                ]
              },
              {
                "type": "sentence-part",
                "words": ", avec dépôt de listes comportant autant de candidats que de sièges à pourvoir"
              }
            ]
          },
          {
            "type": "article-edit",
            "children": [
              {
                "type": "sentence-part",
                "words": "La liste de candidats au conseil municipal comporte un nombre de candidats égal au nombre de sièges à pourvoir, augmenté de deux candidats supplémentaires."
              }
            ],
            "editType": "add"
          }
        ],
        "articleNumber": 1,
        "isNewArticle": false
      },
      {
        "type": "article",
        "children": [
          {
            "type": "article-edit",
            "children": [
              {
                "type": "article-part-reference",
                "children": [],
                "partType": "article",
                "partOffset": "end",
                "partNumber": 2
              },
              {
                "type": "sentence-part",
                "words": "ou de ses communes membres"
              }
            ]
          }
        ],
        "articleNumber": 2,
        "isNewArticle": true
      },
      {
        "type": "article",
        "children": [
          {
            "type": "article-edit",
            "children": [
              {
                "type": "article-content",
                "articleContent": "Jusqu’au renouvellement général du conseil municipal suivant la promulgation de la présente loi, dans les communes de 1 000 habitants et plus, par dérogation au troisième alinéa de l’article L. 2122-8 du code général des collectivités territoriales, lorsqu’il y a lieu de procéder à l’élection du maire, le conseil municipal est réputé complet si les vacances en son sein sont inférieures au dixième de son effectif légal."
              }
            ],
            "editType": "add"
          }
        ],
        "articleNumber": 3,
        "isNewArticle": true
      }
    ]
  }
}
```

I've started pushing the code here:

https://github.com/promethe42/dredd/blob/feature/parser/api/routes/api/parser.js

This approach should solve all the context issues you have.

Do you absolutely want me to rewrite it in python or is it ok to contribute it as a python script ?

**Comment by njoyard** [comment]
Neat :)
While we're at it, why not use a configurable grammar parser and compiler (peg/...) ?

**Comment by promethe42** [comment]
We could use flex/bison. The problem is the actual complete grammar for french might be super hard to properly write.

In the end, we're only interested into some very specific syntaxic constructs. Take a specific law reference: there's only 5 to 7 syntaxic ways it could be written. And with the approach posted above they're pretty easy to match.

So far...

So I'll see if we need something more complex but I don't think so.

**Comment by promethe42** [comment]
AFAIK one one of the biggest issue with the current parser is in some edge cases where articles reference one an other with syntaxes such as "le même article" or "l'article précédent". Which cannot be solved without an AST.

So I decided to put that to the test with the AST method. And it's actually pretty simple to solve using this kind of code:

```javascript
// "le même {number} {part}" or "le même {part}"
if (tokens[i + 4] == 'alinéa' || tokens[i + 6] == 'alinéa') {
    var alineas = searchNode(getRoot(parent), function(n) {
        return n.type == 'article-part-reference' && n.partType == 'alinea'
    });

    node.children.push(alineas[alineas.length - 1]);

    node.partType = 'alinea';

    i += tokens[i + 4] == 'alinéa' ? 6 : 8;
}
```

For example this:

```
Article 1er

Le code général des collectivités territoriales est ainsi modifié :

1° L’article L. 2113-10 est ainsi modifié :

aa (nouveau)) La seconde phrase du premier alinéa est supprimée ;

a) Après le même premier alinéa, il est inséré un alinéa ainsi rédigé :

« Toutefois, à la demande du conseil municipal d’une commune issue d’une fusion de communes, prévue à la section 3 du présent chapitre, dans sa rédaction antérieure à la loi n° 2010-1563 du 16 décembre 2010 de réforme des collectivités territoriales, des communes déléguées reprenant le nom et les limites territoriales de l’ancienne commune chef-lieu et des anciennes communes associées sont instituées. Dans ce cas, il n’est pas créé de commune déléguée reprenant le nom et les limites territoriales de la commune mentionnée à la première phrase du présent alinéa. » ;
```

Will give you this:

```json
{
        "type": "article",
        "children": [
          {
            "type": "header-1",
            "number": 0,
            "children": [
              {
                "type": "article-edit",
                "children": [
                  {
                    "type": "code-reference",
                    "codeName": "code général des collectivités territoriales"
                  }
                ],
                "editType": "edit"
              },
              {
                "type": "header-2",
                "number": 1,
                "children": [
                  {
                    "type": "article-edit",
                    "children": [
                      {
                        "type": "article-reference",
                        "articleId": "L. 2113-10",
                        "children": []
                      }
                    ],
                    "editType": "edit"
                  },
                  {
                    "type": "header-3",
                    "number": 0,
                    "children": [
                      {
                        "type": "article-edit",
                        "children": [
                          {
                            "type": "article-part-reference",
                            "children": [
                              {
                                "type": "article-part-reference",
                                "children": [],
                                "partNumber": 1,
                                "partType": "alinea"
                              }
                            ],
                            "partNumber": 2,
                            "partType": "sentence"
                          }
                        ],
                        "editType": "delete"
                      }
                    ]
                  },
                  {
                    "type": "header-3",
                    "number": 0,
                    "children": [
                      {
                        "type": "article-edit",
                        "children": [
                          {
                            "type": "article-part-reference",
                            "children": [
                              {
                                "type": "article-part-reference",
                                "children": [],
                                "partNumber": 1,
                                "partType": "alinea"
                              }
                            ],
                            "partOffset": "after",
                            "partType": "alinea"
                          },
                          {
                            "type": "article-part-reference",
                            "children": [
                              {
                                "type": "quote",
                                "words": "Toutefois, à la demande du conseil municipal d’une commune issue d’une fusion de communes, prévue à la section 3 du présent chapitre, dans sa rédaction antérieure à la loi n° 2010-1563 du 16 décembre 2010 de réforme des collectivités territoriales, des communes déléguées reprenant le nom et les limites territoriales de l’ancienne commune chef-lieu et des anciennes communes associées sont instituées. Dans ce cas, il n’est pas créé de commune déléguée reprenant le nom et les limites territoriales de la commune mentionnée à la première phrase du présent alinéa."
                              }
                            ],
                            "partType": "alinea"
                          }
                        ],
                        "editType": "add"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        "articleNumber": 1,
        "isNewArticle": false
      }
```

Further enhancements could be made so that lookups would not even be necessary and all references could be fully qualified.

**Comment by promethe42** [comment]
I've forked your repository and ported the code to python:

https://github.com/promethe42/the-law-factory-parser/blob/feature/parse_texte_ast/scripts/collectdata/parse_texte_ast.py

Now I think we should start writting unit tests. Could anyone who has experience with the existing parser help me?

Thanks!

**Comment by RouxRC** [comment]
Ahhh now I understand! :)
Correct me if I'm wrong: your parser translates bills articles into some grammar for modifications on the actual law?
So in fact this is not a "better" parser, just a very different one! and clearly very useful too but out of the actual scope of what LaFabriqueDeLaLoi.fr does!
Our parse_texte.py parser only intends to build actual data instead of document out of a bill. What we need is the text of the bill itself, alinea per alinea. Having references to actual law within is something else which we want to be able to connect at some point but this is not the primary issue. This parser was made to handle this only purpose but made robust for about 1000 different bills versions from various sources, formattings and special outcomes. I still don't understand which context problems you refer to though.

PS: You could have kept the node script it was fine too, although I find the python version more readable.

PS2: You could take back from our code the romans parser which would help handle many cases you haven't yet encountered ;)

**Comment by promethe42** [comment]
> out of the actual scope of what LaFabriqueDeLaLoi.fr does!

That's not what [this slide](https://twitter.com/VirgileDeville/status/725616083399495680) is saying IMHO.

In the end this new script does nothing on itself. But by providing the parsed syntax as an iterable semantic data structure, it makes it possible to do pretty much any computation one would like to perform on such text.

I'm afraid I'm not following you when you're saying that understanding how a bill will changed the existing laws is not in the scope of LaFabriqueDeLaLoi.fr. Because it sounds to me like it's exactly what it's supposed to do...

The existing code even go as far as generating a git repository to track those changes after they happened. One of the things this new parser will allow is to see those changes before they happen. So the deal here is not "what". It's "when".

> You could take back from our code the romans parser which would help handle many cases you haven't yet encountered ;)

Cool. Where is it?

**Comment by fmassot** [comment]
this is really great @promethe42, I was thinking of such a parser to get an AST from a given text and of course it can be directly used for LaFabriqueDeLaLoi.fr ! Don't have time the time right now to look at your code but definitely I think it's the right way to do it.

for the roman parser, everything should be in parse_texte.py ping @RouxRC

**Comment by promethe42** [comment]
> for the roman parser, everything should be in parse_texte.py ping @RouxRC

OK found it. Thanks.

My first priority is on the new bills. So I'll do as much as possible to support say the last 50 bills properly. And I'll write unit tests to make sure it's maintainable.

Then I'll probably need some help if we want it to work on every other bills. I'm sure you have lots of experience and you know how f****d up they are. So that will help :)

**Comment by boogheta** [comment]
@promethe42 This slide of my Barcelona talk was exposing future plans: the connection to actual existing codes of law and their history is the furthest objective, a lot is required before this can actually be doable/usable in TheLawFactory, starting with handling all texts and doing such lex-parsing for amendments first.

When I said "how a bill will change the existing laws is not in the scope of LaFabriqueDeLaLoi.fr" I meant presently: the current status of LFDLL is to track the evolution of the bills themselves. If you conceptualize as git the legislative process, bills are indeed patches/pullrequests to actual laws which are versionned. But these patches have their own lives before they can actually be merged into laws: they are themselves forked via amendments which are patches to the main patch, and have multiple iterations of such PRs accepted before we get to a promulgated bill which is the one you actually apply to codes of law. The first objective of TheLawFactory was to track this first part and is not fully achieved yet although it already works quite well on a wide variety of cases.

IMHO, it is best to cleanly separate tasks:
- there is scraping on one side, which is grabbing html sources for all kind of bills at various steps and making actual data instead of html documents out of it. This is what scripts in this repo are doing, among which parse_texte.py but also other ones down the pipe (especially the complete_articles part which makes everything more complex, see slide 4 of the talk https://www.regardscitoyens.org/presentations/20160428_RegardsCitoyens_TICTec_Barcelona_TheLawFactory.pdf )
- and there is lex-parsing on the other side, which is what you're doing, and would probably be easier  by reusing the data output from the scraper rather than starting over from the html source

This is why I said I'd rather start such lex work from these outputs and not from the bills source html: otherwise you'll have to redo the whole mess dealing with scraping all the crazy different cases of manually drafted bills.

This approach would also allow to factorize this lex-parsing code to apply it as well to amendments, which need to be interpreted/grammarized as well in order to propose bill versions changes the same way you do it with bills as grammar for law changes. Some first tryouts were experimented for this only here: https://github.com/medialab/amendement

**Comment by promethe42** [comment]
> and there is lex-parsing on the other side, which is what you're doing, and would probably be easier by reusing the data output from the scraper rather than starting over from the html source

That's probably right.
I think it should be pretty simple to change my code to use the JSON output indeed.
I'll think about it and give it a try.

> apply it as well to amendments

How different is the syntax? Can you please point to some examples?
I'll probably need that too next.

**Comment by boogheta** [comment]
I feel like it would make our two codes more consistent with each other and complementary this way yes!
If you want to find examples of data outputs for bills version,s you can find plenty in the API under paths such as : https://www.lafabriquedelaloi.fr/api/pjl15-republique_numerique/procedure/00_1%C3%A8relecture_assemblee_depot/texte/texte.json
(just change the text and step IDs to find other ones from https://www.lafabriquedelaloi.fr/api/ )

Regarding amendments they have a very similar syntax to articles ones. You can find plenty of examples in the API as well, for instance here: https://www.lafabriquedelaloi.fr/api/pjl15-republique_numerique/procedure/05_1%C3%A8relecture_senat_hemicycle/amendements/

**Comment by promethe42** [comment]
OK so I've updated my script to work on the JSON output of `parse_texte.py`. Here it is:

https://github.com/promethe42/the-law-factory-parser/blob/feature/parse_texte_ast/scripts/collectdata/parse_texte_edits.py

Here is the output for [pjl12-691](https://www.lafabriquedelaloi.fr/api/pjl12-691/procedure/00_1%C3%A8relecture_assemblee_depot/texte/texte.json):

```json
{
  "children": [
    {
      "articleNumber": 1,
      "children": [
        {
          "children": [
            {
              "articleId": 38,
              "children": [
                {
                  "lawDate": "1958-12-22",
                  "lawId": "58-1270",
                  "lawType": "ordonnance",
                  "type": "law-reference"
                }
              ],
              "type": "article-reference"
            },
            {
              "children": [
                {
                  "type": "quote",
                  "words": "Les dispositions du présent article sont applicables au procureur de la République financier près le tribunal de grande instance de Paris dans les mêmes conditions qu'au procureur de la République près le même tribunal."
                }
              ],
              "partType": "alinea",
              "type": "article-part-reference"
            }
          ],
          "editType": "add",
          "type": "article-edit"
        }
      ],
      "isNew": false,
      "type": "article"
    }
  ]
}
```

Don't you think it would be simpler/better for me to contribute on your repository directly?
I would work in a separate branch for now anyway.
Just let me know.

Now I want to have unit tests and use Travis CI to automate them.
Would you guys be ok with that?

**Comment by promethe42** [comment]
I've added tests using the `unittest` python module.
Those tests are very simple: they compare the output of `parse_texte_edits.py` to some pre-recorded manually validated output files.
Test cases are dynamically generated by listing all the available input test files.

I've also added a config file for Travis CI to run the tests automatically:

https://travis-ci.org/promethe42/the-law-factory-parser

The very same test system could be used for other scripts.
That should greatly reduce regressions.

Are you interested in a pull request?

**Comment by RouxRC** [comment]
Really cool!
Yes a PR will do for now, and yes I added you as a commiter to the repo so you can keep going in a branch or even in master as long as these are complementary scripts, as you wish.
Regarding tests and travis, yes also, we should definitively go towards this anyways for the rest as well (and this is the approach @fmassot & @njoyard have taken already with their anpy senapy and legipy parsers).
I'm setting-up the travis account

**Comment by RouxRC** [comment]
ready to host a travis.yml

**Comment by promethe42** [comment]
> ready to host a .travis.yml https://travis-ci.org/regardscitoyens/the-law-factory-parser

Thanks!

I'm just finishing a few things and I'll merge it.

**Comment by promethe42** [comment]
This is now a separate project available here:

https://github.com/Legilibre/duralex
