### ISSUE TITLE
some tables still posing issues

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory-parser#54]
example here Art 1er bis A
http://www.senat.fr/leg/pjl14-461.html
http://www.senat.fr/leg/tas14-117.html
http://www.assemblee-nationale.fr/14/ta/ta0542.asp

**Comment by mdamien** [comment]
Looks like they work now: https://www.lafabriquedelaloi.fr/articles.html?loi=pjl14-424

**Comment by RouxRC** [comment]
Le coup des guillemets autour des tableaux qu'ils changent tout le temps voire se plantent en en mettant un deux fois (étape CMP commission) est un peu dommage et on a la même chose par exemple sur transparence, je me dis qu'on pourrait : 
- supprimer tous les alinéas `^[\s"]+$`
- dégager des tableaux d'une seule ligne toutes les cellules `<tr><td>["]+</td>` et `<td>["]+</td></tr>`

**Comment by mdamien** [comment]
Vu que les guillemets sont importants, le mieux serait de les normaliser plutôt que les supprimés. Par exemple en sortant les guillemets des tableaux (tout en les gardant dans le même alinéa) dans le deuxième cas. Et en mettant les guillemets sur le même alinéa que le tableau dans le premier.

En clair, faire comme sur les PDF:
![image](https://user-images.githubusercontent.com/1469823/38608163-ea06c9ee-3d7a-11e8-86d4-f3e4f2e19bc4.png)


Et c'est vrai que ce sera utile pour quand on fera les diffs de tableaux.

**Comment by boogheta** [comment]
+1 mais c'est plus compliqué à implémenter que ce que je proposais ;)

**Comment by boogheta** [comment]
et il faudra gérer dans ce cas en plus le cas particulier évoqué avec un doublon de guillemets
