### ISSUE TITLE
Add script to avoid double parsing in a list of urls

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/the-law-factory-parser#72]
When taking a list of urls from the senat and the AN, de-duplicate the dosleg so they are not parsed multiple times

**Comment by mdamien** [comment]
I'm not sure where this would fit, I propose to add a new script `tlfp-dedup-doslegs-urls` to isolate this feature, what do you think ? The script would parse each dosleg and then de-duplicate the urls.

**Comment by boogheta** [comment]
Je verrais plutôt un tlfp-list-doslegs qui effectivement appellerait lui même senapy list et anpy list, parserait et deduperait.

Après j'ai l'impression que ce serait un peu con de retourner que des urls et de recommencer à reparser les dossiers qu'on vient déjà de parser, du coup ptet avoir un même code appelable : 
- soit par tlfp-list-doslegs qui retourne des urls (dossier sénat en prio, an en fallback)
- soit par tlfp-process-doslegs qui lance directement après le dedupe un process sur chaque dossier mergé unique résultant

Et il faudrait probablement dans ce cas répliquer à ces executables les différentes options des outils de liste (only-current, only-promulgated, ...) et de ceux de parsing (quiet, enable-cache, ...)

**Comment by mdamien** [comment]
Another solution: option in anpy doslegs_url to output senat urls

**Comment by boogheta** [comment]
yay ! \o/
