### ISSUE TITLE
Default locale set is not macOS compatible

### ISSUE THREAD

**Issue by davidbgk** [regardscitoyens/the-law-factory-parser#75]
In `common.py`, there is:

```python
locale.setlocale(locale.LC_TIME, 'fr_FR.utf8')
```

Under macOS, it should be:

```python
locale.setlocale(locale.LC_TIME, 'fr_FR.utf-8')
```

So either documenting the set of `LC_TIME` in the installation procedure or be more resilient to failure during the forced locale set.

**Comment by RouxRC** [comment]
seems legit, can you try a PR? Travis will tell whether it is also valid with linux ;)
