### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/the-law-factory-parser#82]
(would be useful for duralex and zam)

- [x] remove dependency links (962c813d89aa18050ce3fbbefd2004edac8c5417)
- [x] use published legipy/anpy (thanks @davidbgk)
- [ ] improve readme ?

**Comment by mdamien** [comment]
Done :) https://pypi.org/project/tlfp/

**Comment by davidbgk** [comment]
Thank you! 🙌 🙇

**Comment by mdamien** [comment]
Hum, tried `pip install tlfp`, and I've still got two things to fix to make it work:

 - [ ] ERROR: legipy 0.1.2 has requirement six<1.12,>=1.11, but you'll have six 1.12.0 which is incompatible. (Just a warning, but a fix is incoming for legipy)
 - [ ] FileNotFoundError: [Errno 2] No such file or directory: '.../docs/valid_procedure.json'

**Comment by mdamien** [comment]
Done :) The version available on PyPI is now working !
