### ISSUE TITLE
Add last pending step (including CC) to all textes en cours

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory-parser#89]
Handle cases where texts are not published in the right order : 
- for instance CC published but not final texte adopté

cf https://github.com/regardscitoyens/the-law-factory-parser/commit/dea0565f3406d5203863f35c179c021679ef5331

~I thought it was already the case, but it seems it is not always the case,  for instance here:
https://www.lafabriquedelaloi.fr/articles.html?loi=ppl17-337 with the TA AN hémicycle is awaiting publication http://www.assemblee-nationale.fr/15/ta/ta0164.asp
pjl17-249~

**Comment by mdamien** [comment]
Action plan to empirically test we always have the predicted step:

 - [ ] load all the "--in-discussion"' texts
 - [ ] check those have the right predicted step

**Comment by mdamien** [comment]
Closed, for now :)

**Comment by boogheta** [comment]
Seems like some cases are still not handled : https://www.lafabriquedelaloi.fr/articles.html?loi=15-ratification_accord_dialogue_politique_ue_cuba

Like for the dates, this should be tested properly in the backend : if we have neither an ongoing step nor an url_jo, we should report an issue

**Comment by mdamien** [comment]
Added an exception raising if this happens: 0c32f716fa2f557c983304c1471920be646a0691
