### ISSUE TITLE
Handle tables in parse_texte.py

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory-parser#9]
examples:
- art 29 terdecies http://www.assemblee-nationale.fr/14/projets/pl1055.asp
- transparence ordinaire vers la fin article complétant tableau des persos nommés par le chef de l'état

**Comment by RouxRC** [comment]
done in branch renseignement in https://github.com/regardscitoyens/the-law-factory-parser/commit/12a08e87885bbbbe97390a0a57b7ab068cf3caee
To be counterchecked on more bills

**Comment by RouxRC** [comment]
done except for minor specific cases listed elsewhere
