### ISSUE TITLE
Finish metrics

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory-parser#91]
extract data from opendata sénat early (like in merge.py)

**Comment by mdamien** [comment]
Long-term goal is to have a easy to download file with all the stats

**Comment by mdamien** [comment]
Related: When the export is done, we should add a simple data-table interface to explore and play with a data a little bit. We could also plug the export into something like Metabase to have as little custom frontend code as possible.

**Comment by boogheta** [comment]
list of points discussed on various metrics:
- [ ] move "Initiative du texte" to "Nature du texte" 
- [ ] reintroduce "Initative du texte" as "Gouvernement", "Assemblée nationale" ou "Sénat" deduced from "Nature du texte"
- [ ] handle ratios augmentation tailles pour caractères/alinéas/articles suivant une formule (new - old)/old
- [ ] handle ratios of articles modified 
- [ ] distinguish final text size within parliament from promulgated (CC)
- [ ] add indicators of censures CC (nb articles censored, total or partial)
- [ ] add nb_etapes corresponding to etapes displayed on LFDLL (cf #109)
- [ ] add nb_amdmts_adoptes_1ere_lecture in each room for olivier ?
- [ ] add nb_intervenants with actual long interventions (remove invectiveurs only) ?
- [ ] deactivate for now (or check and confirm) nb_signataires_JO
- [ ] deactivate for now CC_size
- [ ] add nombre de jours de séances en plus de nb de seances ?

**Comment by boogheta** [comment]
# Notes Réunion 20/11

NB Etapes
- nombre de dépots dans une institution (CMP = 1, AN = 1, Sénat = 1, CC = 1, Congrès = 1)
- nombre de textes
- nombre d'erreurs

ANNEE FIN

TAILLES
  initiale / finale avant saisine /finale = finale avant saisine
x
  en caractères / mots / articles

RATIO TAILLE (finale finale - initiale)
  en caractères / mots / articles

RATIO DIFF TEXTE (finale finale - initiale)

AMENDEMENTS
  all / adoptés
x
  discuté AN / Sénat
x
  discuté en Commission / en Séance
x
  from parl / from gouv

SEANCES
limiter à seance
  AN / Sénat

INTERVENTIONS
limiter à seance
  AN / Sénat

INTERVENANTS UNIQUES
limiter à seance
  AN / Sénat

DERNIERE LECTURE

DERNIERE LECTURE AVEC CHAMBRE

REMOVE TEXTES CITES, KEEP NB

CHANGER DERNIERE COLONNE EN TEXTE MANQUANT (booléen)

PAGE METHODO:
- textes promulgués donc pas censures complètes
- infos sur amendements de commission
- infos sur les inte	rventions

SUR METRIQUES :
Ajouter des lignes de médianes/moyennes par Législature (Défini par année) sans accords

**Comment by mdamien** [comment]
Colonnes à ajouter:

- [x] Année de promulgation
- [ ] Législature de promulgation
- [ ] Nombre de propositions de loi rattachées
- [ ] Nombre de dépôts dans une institution
- [ ] Nombre de textes produits (correspond au nombre de colonnes dans La Fabrique)
- [ ] Nombre initial de mots
- [ ] Nombre final de mots
- [ ] Nombre de mots avant saisine
- [ ] Nombre d'articles avant saisine
- [ ] Croissance du nombre de mots
- [ ] Croissance du nombre de caractères
- [ ] Ajouter la variation Commission / Hémicycle pour les amendements
- [ ] Dernière lecture avec chambre

Colonnes à modifier:

- [ ] Seances/Interventions/Intervenants/Mots: ne garder que les séances en hémicycle
- [ ] "Source données" -> "Texte manquant" (oui/non)

Colonnes à renommer:

- [ ] Taille Initiale -> Nombre initial de caractères
- [ ] Taille Finale -> Nombre final de caractères
- [ ] Taille du texte avant censure du CC -> Nombre de caractères avant saisine

Colonnes à supprimer:

- [ ] Etapes de la procédure (ancien calcul)

**Comment by mdamien** [comment]
And...done ! I opened another issue for another related long-term goal: #115
