### ISSUE TITLE
Python dependencies have multiple incompatible requirements

### ISSUE THREAD

**Issue by tarNeFyS** [regardscitoyens/the-law-factory-parser#92]
When running the command to install python dependencies as stated in the README, the folloing logs appear.

`
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release. You can find discussion regarding this at https://github.com/pypa/pip/issues/4187.
Requirement already satisfied: lawfactory_utils in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (0.1.1)
Requirement already satisfied: senapy in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (0.2.8)
Requirement already satisfied: legipy in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (0.1.0)
Requirement already satisfied: anpy in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (0.1.14)
Requirement already satisfied: metslesliens==1.3.0 in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (1.3.0)
Requirement already satisfied: diff-match-patch==20121119 in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (20121119)
Requirement already satisfied: python-gitlab==1.5.1 in ./venv/lib/python3.6/site-packages (from tlfp==0.0.1) (1.5.1)
Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.6/site-packages (from lawfactory_utils->tlfp==0.0.1) (4.6.3)
Collecting requests (from lawfactory_utils->tlfp==0.0.1)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Requirement already satisfied: lxml==4.1.1 in ./venv/lib/python3.6/site-packages (from lawfactory_utils->tlfp==0.0.1) (4.1.1)
Requirement already satisfied: click==6.7 in ./venv/lib/python3.6/site-packages (from senapy->tlfp==0.0.1) (6.7)
Requirement already satisfied: html5lib==1.0.1 in ./venv/lib/python3.6/site-packages (from senapy->tlfp==0.0.1) (1.0.1)
Requirement already satisfied: dateparser==0.7.0 in ./venv/lib/python3.6/site-packages (from senapy->tlfp==0.0.1) (0.7.0)
Requirement already satisfied: six<1.12,>=1.11 in ./venv/lib/python3.6/site-packages (from legipy->tlfp==0.0.1) (1.11.0)
Requirement already satisfied: urllib3[secure]<1.23,>=1.22 in ./venv/lib/python3.6/site-packages (from legipy->tlfp==0.0.1) (1.22)
Requirement already satisfied: pathlib==1.0.1 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (1.0.1)
Requirement already satisfied: attrs==17.4.0 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (17.4.0)
Requirement already satisfied: slugify==0.0.1 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (0.0.1)
Requirement already satisfied: html2text==2018.1.9 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (2018.1.9)
Requirement already satisfied: mistune==0.8.3 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (0.8.3)
Requirement already satisfied: xmltodict==0.11.0 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (0.11.0)
Requirement already satisfied: future==0.16.0 in ./venv/lib/python3.6/site-packages (from anpy->tlfp==0.0.1) (0.16.0)
Requirement already satisfied: parsimonious in ./venv/lib/python3.6/site-packages (from metslesliens==1.3.0->tlfp==0.0.1) (0.8.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests->lawfactory_utils->tlfp==0.0.1) (2018.8.13)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests->lawfactory_utils->tlfp==0.0.1) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in ./venv/lib/python3.6/site-packages (from requests->lawfactory_utils->tlfp==0.0.1) (2.7)
Requirement already satisfied: webencodings in ./venv/lib/python3.6/site-packages (from html5lib==1.0.1->senapy->tlfp==0.0.1) (0.5.1)
Requirement already satisfied: pytz in ./venv/lib/python3.6/site-packages (from dateparser==0.7.0->senapy->tlfp==0.0.1) (2018.5)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.6/site-packages (from dateparser==0.7.0->senapy->tlfp==0.0.1) (2.7.3)
Requirement already satisfied: tzlocal in ./venv/lib/python3.6/site-packages (from dateparser==0.7.0->senapy->tlfp==0.0.1) (1.5.1)
Requirement already satisfied: regex in ./venv/lib/python3.6/site-packages (from dateparser==0.7.0->senapy->tlfp==0.0.1) (2018.8.17)
**senapy 0.2.8 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.6.3 which is incompatible.
senapy 0.2.8 has requirement requests==2.18.4, but you'll have requests 2.19.1 which is incompatible.
legipy 0.1.0 has requirement requests<2.19,>=2.18, but you'll have requests 2.19.1 which is incompatible.
anpy 0.1.14 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.6.3 which is incompatible.
anpy 0.1.14 has requirement requests==2.18.4, but you'll have requests 2.19.1 which is incompatible.**
`

This is partly due to nearly systematic fixed version in dependencies declaration, specially in anpy, senapy and legipy

The run for one text then fail because of dependancies mismatch.

**Comment by tarNeFyS** [comment]
Part of the issue is https://github.com/regardscitoyens/lawfactory_utils/blob/3daf110608be2fd05667028cd9c093ef57f91ede/setup.py#L29
lawfactory_utils that does not provide the version number.

I am actually not really into the whole provide a specific version for each dependencies without really good reasons.

**Comment by mdamien** [comment]
Thanks, I’ve noticed also there’s a problem with `requests`, maybe we should switch to pipfile.lock (pipenv) or something for dependencies pinning. I’m open to any solution :)

**Comment by boogheta** [comment]
It seems to me like the issue only comes from incoherent dependences version of beautifulsoup and requests in legipy/anpy/senapy I'll try and fix those

**Comment by boogheta** [comment]
should be all good now!

**Comment by boogheta** [comment]
bon a part que j'ai pété les tests de anpy et senapy, je vérifie ce qui pete ;)
