### ISSUE TITLE
Check and fix broken JO urls

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory-parser#98]
```
ppl13-385 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029075711&categorieLien=id
pjl12-701 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029205282&categorieLien=id
pjl12-699 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029205285&categorieLien=id
pjl12-702 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029205288&categorieLien=id
ppl13-397 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029217904&categorieLien=id
pjl13-715 -> https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029313282&categorieLien=id
```

built with:
```rgrep "legifrance" */viz/procedure.json | awk -F '"' '{print $4}' | grep legifrance | sort -u | while read u; do if curl -s "$u" | grep "Aucun document ne correspond à votre demande." > /dev/null; then dossier=`rgrep "$u" */viz/procedure.json | awk -F '/' '{print $1}' | uniq`; echo "$dossier -> $u"; fi;  done```

**Comment by mdamien** [comment]
Draft for the email to signal those errors to the Senate:

> To: dosleg@senat.fr
> Bonjour,
> Dans les dossiers suivants, le lien vers le textes promulgués au Journal Officiel ne renvoi pas vers le texte en question mais vers une erreur 404:
> - [ppl13-385](https://www.senat.fr/dossier-legislatif/ppl13-385.html)
> - [pjl12-701](https://www.senat.fr/dossier-legislatif/pjl12-701.html)
> - [pjl12-699](https://www.senat.fr/dossier-legislatif/pjl12-699.html)
> - [pjl12-702](https://www.senat.fr/dossier-legislatif/pjl12-702.html)
> - [ppl13-397](https://www.senat.fr/dossier-legislatif/ppl13-397.html)
> - [pjl13-715](https://www.senat.fr/dossier-legislatif/pjl13-715.html)
> 
> En espérant que cette information vous soit utile,
> Cordialement,

**Comment by boogheta** [comment]
sent
